### ISSUE TITLE
ERROR:root:addinfourl instance has no attribute 'iterlines'

### ISSUE THREAD

**Issue by salaun-renater** [leifj/pyFF#39]
Hello,

We are running pyff 0.9.3dev

We have a pipeline definition that looks like this:
## Test to trigger the "addinfourl instance has no attribute 'iterlines'" error
- load:
   - http://mds.edugain.org edugain-signer.crt
## Filter test entities
- fork merge remove:
  - select:
    - http://cnb.rediris.es/simplesaml/saml2/idp/metadata.php
- publish: /tmp/all-edugain-metadata.xml

When running pyff it fails:
# /opt/pyff/bin/pyff --loglevel=DEBUG test.fd
...
DEBUG:root:importing builtins from pyff.pipes to find select
DEBUG:root:string lookup http://cnb.rediris.es/simplesaml/saml2/idp/metadata.php
DEBUG:root:basic lookup http://cnb.rediris.es/simplesaml/saml2/idp/metadata.php
DEBUG:root:recursively fetching members from 'http://cnb.rediris.es/simplesaml/saml2/idp/metadata.php'
----------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pyff/lib/python2.6/site-packages/pyFF-0.9.3dev-py2.6.egg/pyff/__init__.py", line 52, in main
    plumbing(p).process(md, state={'batch': True, 'stats': {}})
  File "/opt/pyff/lib/python2.6/site-packages/pyFF-0.9.3dev-py2.6.egg/pyff/pipes/__init__.py", line 165, in process
    self._process(req)
  File "/opt/pyff/lib/python2.6/site-packages/pyFF-0.9.3dev-py2.6.egg/pyff/pipes/__init__.py", line 184, in _process
    ot = pipe(req, *opts)
  File "/opt/pyff/lib/python2.6/site-packages/pyFF-0.9.3dev-py2.6.egg/pyff/pipes/builtins.py", line 135, in fork
    ip._process(ireq)
  File "/opt/pyff/lib/python2.6/site-packages/pyFF-0.9.3dev-py2.6.egg/pyff/pipes/__init__.py", line 184, in _process
    ot = pipe(req, *opts)
  File "/opt/pyff/lib/python2.6/site-packages/pyFF-0.9.3dev-py2.6.egg/pyff/pipes/builtins.py", line 474, in select
    ot = req.md.entity_set(args, name)
  File "/opt/pyff/lib/python2.6/site-packages/pyFF-0.9.3dev-py2.6.egg/pyff/mdrepo.py", line 667, in entity_set
    for ent in self.lookup(member):
  File "/opt/pyff/lib/python2.6/site-packages/pyFF-0.9.3dev-py2.6.egg/pyff/mdrepo.py", line 646, in lookup
    l = self._lookup(member, xp)
  File "/opt/pyff/lib/python2.6/site-packages/pyFF-0.9.3dev-py2.6.egg/pyff/mdrepo.py", line 607, in _lookup
    return [self._lookup(line, xp) for line in urllib.urlopen(member).iterlines()]
AttributeError: addinfourl instance has no attribute 'iterlines'
----------------------------------------------------------------
ERROR:root:addinfourl instance has no attribute 'iterlines'

I guess the error happens because the edugain metadata no more includes entity http://cnb.rediris.es/simplesaml/saml2/idp/metadata.php. Should I adapt the pipeline definition to prevent pyff to die ?

**Comment by leifj** [comment]
I don't think merge remove works at all after the new store backend was implemented. Working on this regression now.

**Comment by leifj** [comment]
I think I have patched merge now and added a filter method that can be used to accomplish blacklisting. Here is an example from the testcase:
```yaml
- when batch:
    - load:
        - some/metadata via blacklist_example
    - loadstats
- when blacklist_example:
    - fork merge remove:
        - filter:
            - https://idp.example.com/saml2/idp/metadata.php
```

**Comment by salaun-renater** [comment]
I tested the filter pipeline; it worked fine for me.

Note that I also tried to reproduce my earlier issue that made pyff script die (if a selected entityID did not exist in metadata): the latest version of pyff seems to cope with that without dying. Great.

**Comment by leifj** [comment]
Excellent!
