### ISSUE TITLE
MXD query path

### ISSUE THREAD

**Issue by rhoerbe** [leifj/pyFF#43]
querying for an entityId results in an HTTP 404 or 500 status.

E.g. calling up http://mdx.test.portalverbund.gv.at:8081/entities; extracting the entityID https://v-portal.tirol.gv.at/IdPWeb/shibboleth from it; append it urlencoded to the path results in HTTP 500.

The log at http://mdx.test.portalverbund.gv.at:8081 says: 

```
GET /entities/https:%2F%2Fv-portal.tirol.gv.at%2FIdPWeb%2Fshibboleth 

37.221.197.149 - - [15/Jan/2014:21:17:13] "GET /entities/https:%2F%2Fv-portal.tirol.gv.at%2FIdPWeb%2Fshibboleth HTTP/1.1" 500 4053 "" "curl/7.19.7 (i386-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2"
[15/Jan/2014:21:17:56]  request path: https://v-portal.tirol.gv, ext: at/IdPWeb/shibboleth, headers: {'Remote-Addr': '37.221.197.149', 'Host': 'mdx.test.portalverbund.gv.at:8081', 'Accept': 'application/samlmetadata+xml', 'User-Agent': 'curl/7.19.7 (i386-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2'}
[15/Jan/2014:21:17:56]  Processing
. . .
[15/Jan/2014:21:17:56]  string lookup https://v-portal.tirol.gv
[15/Jan/2014:21:17:56]  basic lookup https://v-portal.tirol.gv
[15/Jan/2014:21:17:56]  recursively fetching members from 'https://v-portal.tirol.gv'
[15/Jan/2014:21:17:56] HTTP Traceback (most recent call last):
  File "/var/virtualenv/pyff/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
. . . 
  File "/var/virtualenv/pyff/lib/python2.7/site-packages/pyFF-0.10.0dev-py2.7.egg/pyff/mdrepo.py", line 699, in _lookup
    return [self._lookup(line, xp) for line in urllib.urlopen(member).iterlines()]
AttributeError: addinfourl instance has no attribute 'iterlines'

37.221.197.149 - - [15/Jan/2014:21:17:56] "GET /entities/https:%2F%2Fv-portal.tirol.gv.at%2FIdPWeb%2Fshibboleth HTTP/1.1" 500 4053 "" "curl/7.19.7 (i386-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2"

```
It appears to me that the transformation from PATHINFO to the entityID is broken, because it takes everything after the last dot as an extension, in this case  at/IdPWeb/shibboleth. So it is looking for https://v-portal.tirol.gv, which is not the full entityID.

**Comment by leifj** [comment]
Reviewing issues, this must have gotten fixed because it seems to work now but I will add a testcase and close
