### ISSUE TITLE
bin/buildout gives error on master branch

### ISSUE THREAD

**Issue by remold** [leifj/pyFF#58]
I am unable to 'build' the latest release of pyFF. After git clone of master:

# python bootstrap.py
Creating directory '/root/git/pyFF/bin'.
Creating directory '/root/git/pyFF/parts'.
Creating directory '/root/git/pyFF/eggs'.
Creating directory '/root/git/pyFF/develop-eggs'.
Generated script '/root/git/pyFF/bin/buildout'.

# bin/buildout
While:
  Installing.
  Checking for upgrades.
  Getting distribution for 'zc.buildout>=2.3.1'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/root/git/pyFF/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1946, in main
    getattr(buildout, command)(args)
  File "/root/git/pyFF/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 475, in install
    self._maybe_upgrade()
  File "/root/git/pyFF/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 910, in _maybe_upgrade
    allow_hosts = self._allow_hosts
  File "/root/git/pyFF/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 848, in install
    return installer.install(specs, working_set)
  File "/root/git/pyFF/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 635, in install
    for_buildout_run=for_buildout_run):
  File "/root/git/pyFF/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 477, in _get_dist
    dist, avail = self._satisfied(requirement)
  File "/root/git/pyFF/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 253, in _satisfied
    if _final_version(dist.parsed_version)
  File "/root/git/pyFF/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/easy_install.py", line 1408, in _final_version
    return not parsed_version.is_prerelease
AttributeError: 'tuple' object has no attribute 'is_prerelease'

**Comment by leifj** [comment]
The buildout script is pretty old. It should probably be removed. Please use ./setup.py instead.
